name: Build and Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/html-azure-docker:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Étape 4 : Installer Azure CLI (au lieu d'utiliser azure/cli@v1)
      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      # Étape 5 : Se connecter à Azure
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Étape 6 : Se connecter au registre Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name htmldockerregistry

      # Étape 7 : Déployer sur Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp create --resource-group hamzaResourceGroup \
            --plan hamzaAppPlan \  # Remplacez par le nom de votre plan App Service
            --name hamzaHtmlApp  \
            --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/html-azure-docker:latest
